version: '3'

services:
  cribbage-server:
    build: ./TestServer
    image: jamesfdickinson/test-server
    restart: always
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
  
  
